// Sprint mock data — replace with API calls when backend is live.

const P = (id) => `https://images.unsplash.com/photo-${id}?w=800&q=80`;

const PHOTOS = {
  pool1:    P('1571896349842-33c89424de2d'),
  rice:     P('1537996194471-e657df975ab4'),
  pool2:    P('1552733407-5d5c46c3bb3b'),
  poolDeck: P('1580587771525-4cad66a7af52'),
  poolRefl: P('1516815231560-8f41ec531527'),
  outdoor:  P('1582268611958-ebfd161ef9cf'),
  bedroom:  P('1499793983690-e29da9de2287'),
  poolUmb:  P('1523531294919-4bcd7c65d49b'),
  beach:    P('1519046904884-53103b34b206'),
  cliff:    P('1566073771259-470de1c49b4d'),
  exterior: P('1558618666-fcd25c85cd64'),
  living:   P('1619546813926-a78fa6372cd2'),
  bathoom:  P('1584132967334-10e028bd69f7'),
  aerial:   P('1543422328-80906e78e59c'),
  sunset:   P('1535913989690-f90e1c2d4cfa'),
};

const av = (name, bg = '9BB8B0') =>
  `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=${bg}&color=fff&size=64`;

const REGION_PHOTO_MAP = {
  'Ubud':     '/ubud.jpg',
  'Seminyak': '/seminyak.jpg',
  'Canggu':   '/canggu.jpg',
  'Uluwatu':  '/uluwatu.jpg',
  'Sanur':    '/sanur.jpg',
  'Nusa Dua': '/nusa-dua.jpg',
};

const GALLERY_SETS = [
  ['/Villa1.jpg', '/Villa2.jpg', '/Villa3.jpg'],
  ['/Villa2.jpg', '/Villa3.jpg', '/Villa1.jpg'],
  ['/Villa3.jpg', '/Villa1.jpg', '/Villa2.jpg'],
];

/**
 * Replace any external (http) photo URLs on an API-returned villa with local files.
 * No-op if the villa already has local photos.
 * @param {object} villa
 * @param {number} [index]
 * @returns {object}
 */
export function normalizeVillaPhotos(villa, index = 0) {
  if (!villa) return villa;
  const photos = villa.photos ?? [];
  const allLocal = photos.length > 0 && photos.every((p) => !p?.startsWith('http'));
  if (allLocal) return villa;
  const primary = REGION_PHOTO_MAP[villa.region] ?? '/landing.jpg';
  const rotation = (typeof villa.id === 'number' ? Math.floor(villa.id / 3) + index : index) % 3;
  return { ...villa, photos: [primary, ...GALLERY_SETS[rotation]] };
}

// ─── HOSTS ───────────────────────────────────────────────────────────────────

export const HOSTS = [
  {
    id: 'host-1',
    displayName: 'Wayan Sudana',
    avatarUrl: 'https://ui-avatars.com/api/?name=Wayan+Sudana&background=1F6B5C&color=fff&size=128',
    hostingSince: 2019,
    responseRate: 98,
    languages: ['Bahasa Indonesia', 'English'],
    bio: "Born and raised in Ubud, I've spent a decade curating exceptional villa experiences for travellers from around the world. My properties are my passion — every detail has been chosen with care.",
    listings: ['villa-1', 'villa-6', 'villa-11'],
    totalRevenuIdr: 485000000,
    avgRating: 9.4,
    totalBookings: 87,
  },
  {
    id: 'host-2',
    displayName: 'Made Suartika',
    avatarUrl: 'https://ui-avatars.com/api/?name=Made+Suartika&background=144A3F&color=fff&size=128',
    hostingSince: 2018,
    responseRate: 99,
    languages: ['Bahasa Indonesia', 'English', 'Japanese'],
    bio: "After 15 years in hospitality management at five-star Bali resorts, I now focus on my family's private villas. Guests are family — I treat every stay as if you're visiting my home.",
    listings: ['villa-2', 'villa-7', 'villa-12'],
    totalRevenuIdr: 720000000,
    avgRating: 9.7,
    totalBookings: 124,
  },
  {
    id: 'host-3',
    displayName: 'Ketut Wijaya',
    avatarUrl: 'https://ui-avatars.com/api/?name=Ketut+Wijaya&background=9BB8B0&color=fff&size=128',
    hostingSince: 2020,
    responseRate: 96,
    languages: ['Bahasa Indonesia', 'English'],
    bio: "Third-generation Balinese architect turned host. Each of my villas is a reflection of traditional Balinese design philosophy — natural materials, open spaces, and harmony with the land.",
    listings: ['villa-3', 'villa-8'],
    totalRevenuIdr: 312000000,
    avgRating: 9.2,
    totalBookings: 67,
  },
  {
    id: 'host-4',
    displayName: 'Nyoman Artana',
    avatarUrl: 'https://ui-avatars.com/api/?name=Nyoman+Artana&background=C9A961&color=fff&size=128',
    hostingSince: 2017,
    responseRate: 97,
    languages: ['Bahasa Indonesia', 'English', 'Dutch'],
    bio: "I manage six villas across Canggu and Seminyak for an international ownership group. Local knowledge, professional service — I'm here to make your Bali trip unforgettable.",
    listings: ['villa-4', 'villa-9'],
    totalRevenuIdr: 560000000,
    avgRating: 9.3,
    totalBookings: 203,
  },
  {
    id: 'host-5',
    displayName: 'Putu Dewi',
    avatarUrl: 'https://ui-avatars.com/api/?name=Putu+Dewi&background=6B8A82&color=fff&size=128',
    hostingSince: 2021,
    responseRate: 95,
    languages: ['Bahasa Indonesia', 'English'],
    bio: "Former travel consultant now living my dream — sharing Bali's beauty from the inside. My villas in Sanur and Nusa Dua are designed for families who want calm, space, and the sea.",
    listings: ['villa-5', 'villa-10'],
    totalRevenuIdr: 218000000,
    avgRating: 9.2,
    totalBookings: 89,
  },
];

// ─── VILLAS ──────────────────────────────────────────────────────────────────

export const VILLAS = [
  {
    id: 'villa-1',
    slug: 'villa-tjampuhan-ubud',
    titleEn: 'Villa Tjampuhan Ubud',
    titleZh: '乌布德查潘汉别墅',
    location: 'Ubud · 5 min to Campuhan Ridge Walk',
    region: 'Ubud',
    bedrooms: 3, beds: 4, bathrooms: 3, maxGuests: 6,
    basePriceIdr: 4500000, basePriceCny: 2088,
    rating: 9.4, reviewCount: 87,
    photos: [PHOTOS.rice, PHOTOS.pool1, PHOTOS.bedroom, PHOTOS.living, PHOTOS.bathoom],
    amenities: ['pool', 'wifi', 'ac', 'kitchen', 'hottub'],
    highlights: ['peaceful', 'unique'],
    badges: ['balivilla_select'],
    status: 'published',
    instantBook: true,
    descriptionEn: "Perched above the Campuhan River valley, this intimate retreat offers sweeping rice terrace views and a heated infinity pool that merges with the jungle horizon at sunset. A private chef can be arranged to prepare traditional Balinese or Chinese dishes in the fully equipped open kitchen.",
    descriptionZh: "依偎于乌布查潘汉河谷之上，这处宁静的隐居地可俯瞰连绵稻田美景，加热无边泳池与丛林地平线相融。可安排私人厨师，在设备齐全的开放式厨房烹制传统巴厘岛与中式佳肴。",
    hostId: 'host-1',
  },
  {
    id: 'villa-2',
    slug: 'villa-karang-putih-uluwatu',
    titleEn: 'Villa Karang Putih Uluwatu',
    titleZh: '乌鲁瓦图白礁悬崖别墅',
    location: 'Uluwatu · Cliffside · 3 min to Single Fin',
    region: 'Uluwatu',
    bedrooms: 4, beds: 5, bathrooms: 4, maxGuests: 8,
    basePriceIdr: 8500000, basePriceCny: 3942,
    rating: 9.7, reviewCount: 124,
    photos: [PHOTOS.cliff, PHOTOS.pool1, PHOTOS.outdoor, PHOTOS.bedroom, PHOTOS.sunset],
    amenities: ['pool', 'wifi', 'ac', 'beachaccess', 'bbq'],
    highlights: ['stylish', 'unique'],
    badges: ['guest_favorite', 'balivilla_select'],
    status: 'published',
    instantBook: false,
    descriptionEn: "Dramatically positioned on Uluwatu's limestone cliffs, Villa Karang Putih delivers uninterrupted Indian Ocean views from every room. The cantilevered infinity pool hovers 70 metres above the surf, and the rooftop terrace is the finest perch in South Bali to watch the sun disappear.",
    descriptionZh: "壮观地矗立于乌鲁瓦图石灰岩峭壁之上，白礁别墅每个房间均享有无遮挡的印度洋海景。悬臂式无边泳池悬浮于海浪上方七十米处，屋顶露台是南巴厘岛观赏日落的绝佳之地。",
    hostId: 'host-2',
  },
  {
    id: 'villa-3',
    slug: 'villa-puri-seminyak',
    titleEn: 'Villa Puri Seminyak',
    titleZh: '水明漾普里宫殿别墅',
    location: 'Seminyak · 5 min walk to Seminyak Beach',
    region: 'Seminyak',
    bedrooms: 5, beds: 6, bathrooms: 5, maxGuests: 10,
    basePriceIdr: 12000000, basePriceCny: 5568,
    rating: 9.2, reviewCount: 203,
    photos: [PHOTOS.poolDeck, PHOTOS.pool2, PHOTOS.living, PHOTOS.bedroom, PHOTOS.exterior],
    amenities: ['pool', 'wifi', 'ac', 'kitchen', 'bbq', 'parking'],
    highlights: ['central', 'spacious'],
    badges: ['instant_book'],
    status: 'published',
    instantBook: true,
    descriptionEn: "A modern Balinese palace in the heart of Seminyak, Villa Puri places you moments from the island's finest restaurants, beach clubs, and boutiques. Five ensuite bedrooms surround a 20-metre pool and shaded joglo pavilion that becomes party central by night.",
    descriptionZh: "坐落于水明漾核心地带的现代巴厘宫殿，普里别墅距岛上最佳餐厅、海滩俱乐部和精品店仅咫尺之遥。五间独立卫浴套房环绕着二十米长泳池和遮阴传统阁楼凉亭，夜晚这里便成为派对中心。",
    hostId: 'host-3',
  },
  {
    id: 'villa-4',
    slug: 'villa-daun-canggu',
    titleEn: 'Villa Daun Canggu',
    titleZh: '水流通竹叶艺术别墅',
    location: 'Canggu · 2 min to Batu Bolong Beach',
    region: 'Canggu',
    bedrooms: 3, beds: 3, bathrooms: 3, maxGuests: 6,
    basePriceIdr: 5500000, basePriceCny: 2552,
    rating: 9.5, reviewCount: 156,
    photos: [PHOTOS.pool2, PHOTOS.outdoor, PHOTOS.bedroom, PHOTOS.living, PHOTOS.exterior],
    amenities: ['pool', 'wifi', 'ac', 'kitchen', 'bbq'],
    highlights: ['stylish', 'central'],
    badges: ['guest_favorite', 'instant_book'],
    status: 'published',
    instantBook: true,
    descriptionEn: "An architect's masterpiece hidden down a quiet Canggu lane, Villa Daun fuses raw concrete and tropical greenery into something genuinely striking. Two minutes on foot puts you at Batu Bolong, the most lively stretch of Canggu beach, yet the villa's high walls make it a world apart.",
    descriptionZh: "藏在水流通一条宁静小巷里的建筑杰作，竹叶别墅将原始混凝土与热带绿植融为一体，创造出令人印象深刻的视觉奇观。步行两分钟即可到达水流通最热闹的芭杜博朗海滩，而别墅的高墙又将其与外界完全隔绝。",
    hostId: 'host-4',
  },
  {
    id: 'villa-5',
    slug: 'villa-segara-sanur',
    titleEn: 'Villa Segara Sanur',
    titleZh: '沙努尔碧海海滨别墅',
    location: 'Sanur · Beachfront · Direct beach access',
    region: 'Sanur',
    bedrooms: 4, beds: 5, bathrooms: 4, maxGuests: 8,
    basePriceIdr: 7200000, basePriceCny: 3341,
    rating: 9.3, reviewCount: 98,
    photos: [PHOTOS.beach, PHOTOS.poolRefl, PHOTOS.poolDeck, PHOTOS.bedroom, PHOTOS.living],
    amenities: ['pool', 'wifi', 'ac', 'beachaccess', 'parking'],
    highlights: ['family', 'peaceful'],
    badges: ['guest_favorite'],
    status: 'published',
    instantBook: false,
    descriptionEn: "Directly on Sanur's calm reef-protected beach, Villa Segara is the ideal base for families. Step through the garden gate and your toes are in the sand; step back inside to a 14-metre pool, four king bedrooms, and a fully staffed villa team at your service.",
    descriptionZh: "直接毗邻沙努尔平静礁石保护海滩，碧海别墅是家庭度假的理想选择。穿过花园大门，脚趾便触碰到细沙；返回室内，有十四米长泳池、四间大床套房和全职别墅服务团队恭候。",
    hostId: 'host-5',
  },
  {
    id: 'villa-6',
    slug: 'villa-bukit-nusa-dua',
    titleEn: 'Villa Bukit Nusa Dua',
    titleZh: '努沙杜阿布基特豪华别墅',
    location: 'Nusa Dua · Resort district · Private beach path',
    region: 'Nusa Dua',
    bedrooms: 6, beds: 7, bathrooms: 6, maxGuests: 12,
    basePriceIdr: 18000000, basePriceCny: 8352,
    rating: 9.6, reviewCount: 67,
    photos: [PHOTOS.pool1, PHOTOS.beach, PHOTOS.outdoor, PHOTOS.living, PHOTOS.bathoom],
    amenities: ['pool', 'wifi', 'ac', 'kitchen', 'bbq', 'beachaccess'],
    highlights: ['family', 'stylish'],
    badges: ['balivilla_select'],
    status: 'published',
    instantBook: false,
    descriptionEn: "The grandest property in our Nusa Dua portfolio, Villa Bukit accommodates up to twelve guests in six ocean-view suites surrounding an enormous 25-metre pool. A private path leads directly to the white sand beach, and the dedicated butler coordinates everything from daily breakfast to evening cocktails.",
    descriptionZh: "努沙杜阿套系中最宏伟的物业，布基特别墅在环绕二十五米大型泳池的六间海景套房中可容纳多达十二位宾客。私人小径直通白沙海滩，专属管家为您协调每日早餐至晚间鸡尾酒的一切安排。",
    hostId: 'host-1',
  },
  {
    id: 'villa-7',
    slug: 'villa-sawah-ubud',
    titleEn: 'Villa Sawah Ubud',
    titleZh: '乌布稻田秘境别墅',
    location: 'Ubud · Rice terrace views · Near Tegallalang',
    region: 'Ubud',
    bedrooms: 2, beds: 2, bathrooms: 2, maxGuests: 4,
    basePriceIdr: 3200000, basePriceCny: 1485,
    rating: 9.8, reviewCount: 241,
    photos: [PHOTOS.rice, PHOTOS.poolRefl, PHOTOS.bedroom, PHOTOS.living, PHOTOS.outdoor],
    amenities: ['pool', 'wifi', 'ac', 'hottub'],
    highlights: ['peaceful', 'unique'],
    badges: ['guest_favorite', 'balivilla_select'],
    status: 'published',
    instantBook: true,
    descriptionEn: "The most-reviewed villa in our Ubud collection, Villa Sawah earns its perfect scores through sheer romance — a plunge pool perched above ancient rice terraces, outdoor rain shower, and beds facing the valley so you wake to green and gold. Ideal for couples celebrating something special.",
    descriptionZh: "我们乌布精选中评价最多的别墅，稻田别墅凭借纯粹的浪漫氛围赢得满分佳评——俯瞰古老稻田的泳池、户外雨淋浴、面朝山谷的床铺让您在绿意金光中苏醒。最适合情侣庆祝特殊时刻。",
    hostId: 'host-2',
  },
  {
    id: 'villa-8',
    slug: 'villa-batu-uluwatu',
    titleEn: 'Villa Batu Uluwatu',
    titleZh: '乌鲁瓦图巨岩海景别墅',
    location: 'Uluwatu · Ocean views · Near Pura Uluwatu',
    region: 'Uluwatu',
    bedrooms: 3, beds: 4, bathrooms: 3, maxGuests: 6,
    basePriceIdr: 6800000, basePriceCny: 3155,
    rating: 9.4, reviewCount: 112,
    photos: [PHOTOS.cliff, PHOTOS.pool2, PHOTOS.bedroom, PHOTOS.sunset, PHOTOS.outdoor],
    amenities: ['pool', 'wifi', 'ac', 'beachaccess'],
    highlights: ['stylish', 'unique'],
    badges: ['instant_book'],
    status: 'published',
    instantBook: true,
    descriptionEn: "Carved into Uluwatu's volcanic rock, Villa Batu feels like a private fortress on the edge of the world. Three generous suites open onto ocean-facing terraces, the plunge pool glows blue against the limestone, and the kecak fire dance at the nearby temple is visible from your sunlounger.",
    descriptionZh: "凿入乌鲁瓦图火山岩之中，巨岩别墅犹如世界边缘的私人堡垒。三间宽敞套房朝向海洋露台敞开，水池在石灰岩映衬下泛着蓝光，附近神庙的克差火舞从您的躺椅上便可欣赏。",
    hostId: 'host-3',
  },
  {
    id: 'villa-9',
    slug: 'villa-pantai-seminyak',
    titleEn: 'Villa Pantai Seminyak',
    titleZh: '水明漾海滩花园别墅',
    location: 'Seminyak · 2 min walk to Petitenget Beach',
    region: 'Seminyak',
    bedrooms: 4, beds: 5, bathrooms: 4, maxGuests: 8,
    basePriceIdr: 9500000, basePriceCny: 4407,
    rating: 9.1, reviewCount: 178,
    photos: [PHOTOS.poolDeck, PHOTOS.pool1, PHOTOS.living, PHOTOS.bedroom, PHOTOS.exterior],
    amenities: ['pool', 'wifi', 'ac', 'kitchen'],
    highlights: ['central', 'spacious'],
    badges: [],
    status: 'published',
    instantBook: false,
    descriptionEn: "Set behind a lush garden wall two minutes from Petitenget Beach, Villa Pantai combines Seminyak's unbeatable position with residential privacy. Four bedrooms, a 16-metre pool, and a kitchen stocked daily by the caretaker team make this an easy base for a group holiday.",
    descriptionZh: "藏在距佩蒂登盖海滩两分钟路程的郁郁葱葱花园墙后，海滩别墅将水明漾无与伦比的地理位置与居家隐私完美结合。四间卧室、十六米长泳池，加上每日由看护团队备货的厨房，让这里成为团体假期的轻松根据地。",
    hostId: 'host-4',
  },
  {
    id: 'villa-10',
    slug: 'villa-pererenan-canggu',
    titleEn: 'Villa Pererenan Canggu',
    titleZh: '水流通北部日落别墅',
    location: 'Canggu · Quiet lane · 10 min to Echo Beach',
    region: 'Canggu',
    bedrooms: 2, beds: 3, bathrooms: 2, maxGuests: 4,
    basePriceIdr: 3800000, basePriceCny: 1763,
    rating: 9.0, reviewCount: 89,
    photos: [PHOTOS.pool2, PHOTOS.outdoor, PHOTOS.bedroom, PHOTOS.living, PHOTOS.aerial],
    amenities: ['pool', 'wifi', 'ac', 'bbq'],
    highlights: ['stylish', 'central'],
    badges: ['instant_book'],
    status: 'published',
    instantBook: true,
    descriptionEn: "A compact, stylish villa in the quieter northern stretch of Canggu, Villa Pererenan is perfect for two couples or a small family who want surf town energy without the crowds. The rooftop BBQ deck catches the famous Canggu sunset every evening.",
    descriptionZh: "位于水流通北部较安静地带的精巧时尚别墅，北部日落别墅非常适合两对情侣或小家庭，既能感受冲浪小镇的活力，又远离人群喧嚣。屋顶烧烤露台每晚都能欣赏到水流通著名的日落美景。",
    hostId: 'host-5',
  },
  {
    id: 'villa-11',
    slug: 'villa-sindhu-sanur',
    titleEn: 'Villa Sindhu Sanur',
    titleZh: '沙努尔辛度家庭度假别墅',
    location: 'Sanur · 5 min walk to Sindhu Beach',
    region: 'Sanur',
    bedrooms: 3, beds: 4, bathrooms: 3, maxGuests: 6,
    basePriceIdr: 5800000, basePriceCny: 2691,
    rating: 9.2, reviewCount: 143,
    photos: [PHOTOS.poolRefl, PHOTOS.beach, PHOTOS.bedroom, PHOTOS.living, PHOTOS.exterior],
    amenities: ['pool', 'wifi', 'ac', 'parking'],
    highlights: ['family', 'peaceful'],
    badges: ['guest_favorite'],
    status: 'published',
    instantBook: false,
    descriptionEn: "Sanur's calm, shallow seas make it the best part of Bali for families with young children, and Villa Sindhu is precisely calibrated for that market. The pool has a shallow wading section for little ones, there are three spacious bedrooms, and the neighbourhood is safe, walkable, and full of good restaurants.",
    descriptionZh: "沙努尔平静的浅海使其成为巴厘岛最适合带幼儿家庭的区域，辛度别墅正是为此量身打造。泳池设有儿童浅水区，三间宽敞卧室，周边社区安全宜步行，餐厅众多。",
    hostId: 'host-1',
  },
  {
    id: 'villa-12',
    slug: 'villa-tanjung-nusa-dua',
    titleEn: 'Villa Tanjung Nusa Dua',
    titleZh: '努沙杜阿丹宗私人海滩别墅',
    location: 'Nusa Dua · Resort district · Private beach',
    region: 'Nusa Dua',
    bedrooms: 5, beds: 6, bathrooms: 5, maxGuests: 10,
    basePriceIdr: 14500000, basePriceCny: 6727,
    rating: 9.5, reviewCount: 88,
    photos: [PHOTOS.beach, PHOTOS.pool1, PHOTOS.living, PHOTOS.bedroom, PHOTOS.bathoom],
    amenities: ['pool', 'wifi', 'ac', 'kitchen', 'beachaccess'],
    highlights: ['spacious', 'stylish'],
    badges: ['balivilla_select'],
    status: 'published',
    instantBook: false,
    descriptionEn: "Five elegantly appointed suites on a private stretch of white Nusa Dua sand — Villa Tanjung is unapologetically luxurious. The 22-metre pool runs parallel to the sea, daily breakfast is included, and the full-time housekeeper ensures the villa is always immaculate.",
    descriptionZh: "坐落于努沙杜阿私人白沙海滩上的五间精致套房，丹宗别墅毫不掩饰其奢华本质。二十二米长泳池与大海平行延伸，每日早餐已含，全职管家确保别墅随时一尘不染。",
    hostId: 'host-2',
  },
];

// ─── HOST BOOKINGS ────────────────────────────────────────────────────────────
// Host-perspective bookings — used on reservations, calendar, and insights pages.

export const HOST_BOOKINGS = [
  { id: 'hbk-01', villaId: 'villa-1', guestName: '李明',   guestAvatarUrl: av('李明', '1F6B5C'),   checkIn: '2026-06-05', checkOut: '2026-06-10', nights: 5, adults: 2, children: 0, status: 'confirmed',        totalCny: 10440, totalIdr: 22500000, payoutIdr: 19350000 },
  { id: 'hbk-02', villaId: 'villa-1', guestName: 'Emma K.', guestAvatarUrl: av('Emma K', '144A3F'), checkIn: '2026-06-18', checkOut: '2026-06-25', nights: 7, adults: 2, children: 0, status: 'confirmed',        totalCny: 14616, totalIdr: 31500000, payoutIdr: 27090000 },
  { id: 'hbk-03', villaId: 'villa-6', guestName: '林敏',   guestAvatarUrl: av('林敏', '9BB8B0'),   checkIn: '2026-07-10', checkOut: '2026-07-17', nights: 7, adults: 8, children: 4, status: 'confirmed',        totalCny: 58464, totalIdr: 126000000, payoutIdr: 108360000 },
  { id: 'hbk-04', villaId: 'villa-1', guestName: 'Thomas B.', guestAvatarUrl: av('Thomas B', '6B8A82'), checkIn: '2026-05-20', checkOut: '2026-05-24', nights: 4, adults: 4, children: 0, status: 'in_house',    totalCny: 8352,  totalIdr: 18000000,  payoutIdr: 15480000 },
  { id: 'hbk-05', villaId: 'villa-6', guestName: '王芳',   guestAvatarUrl: av('王芳', 'C9A961'),   checkIn: '2026-05-15', checkOut: '2026-05-20', nights: 5, adults: 10, children: 2, status: 'completed',       totalCny: 41760, totalIdr: 90000000,  payoutIdr: 77400000 },
  { id: 'hbk-06', villaId: 'villa-11', guestName: '张伟',  guestAvatarUrl: av('张伟', '1F6B5C'),   checkIn: '2026-08-01', checkOut: '2026-08-07', nights: 6, adults: 2, children: 2, status: 'confirmed',        totalCny: 16146, totalIdr: 34800000,  payoutIdr: 29928000 },
  { id: 'hbk-07', villaId: 'villa-1', guestName: 'Sarah M.', guestAvatarUrl: av('Sarah M', '144A3F'), checkIn: '2026-05-01', checkOut: '2026-05-05', nights: 4, adults: 2, children: 0, status: 'completed',   totalCny: 8352,  totalIdr: 18000000,  payoutIdr: 15480000 },
  { id: 'hbk-08', villaId: 'villa-6', guestName: '陈静',   guestAvatarUrl: av('陈静', '9BB8B0'),   checkIn: '2026-09-05', checkOut: '2026-09-12', nights: 7, adults: 12, children: 0, status: 'pending_approval', totalCny: 58464, totalIdr: 126000000, payoutIdr: 108360000 },
  { id: 'hbk-09', villaId: 'villa-11', guestName: 'David L.', guestAvatarUrl: av('David L', '6B8A82'), checkIn: '2026-07-20', checkOut: '2026-07-25', nights: 5, adults: 2, children: 1, status: 'confirmed', totalCny: 13455, totalIdr: 29000000,  payoutIdr: 24940000 },
  { id: 'hbk-10', villaId: 'villa-1', guestName: '刘洋',   guestAvatarUrl: av('刘洋', '1F6B5C'),   checkIn: '2026-04-10', checkOut: '2026-04-15', nights: 5, adults: 6, children: 0, status: 'completed',        totalCny: 10440, totalIdr: 22500000,  payoutIdr: 19350000 },
  { id: 'hbk-11', villaId: 'villa-6', guestName: 'James T.', guestAvatarUrl: av('James T', '144A3F'), checkIn: '2026-10-01', checkOut: '2026-10-08', nights: 7, adults: 4, children: 2, status: 'confirmed',  totalCny: 58464, totalIdr: 126000000, payoutIdr: 108360000 },
  { id: 'hbk-12', villaId: 'villa-11', guestName: '赵晓丽', guestAvatarUrl: av('赵晓丽', 'C9A961'), checkIn: '2026-05-22', checkOut: '2026-05-27', nights: 5, adults: 4, children: 2, status: 'pending_approval', totalCny: 13455, totalIdr: 29000000, payoutIdr: 24940000 },
];

// ─── CONVERSATIONS ────────────────────────────────────────────────────────────

export const CONVERSATIONS = [
  {
    id: 'conv-1',
    villaId: 'villa-7',
    guestId: 'guest-001',
    hostId: 'host-2',
    guestName: '李明',
    hostName: 'Made Suartika',
    guestAvatar: av('李明', '1F6B5C'),
    hostAvatar: 'https://ui-avatars.com/api/?name=Made+Suartika&background=144A3F&color=fff&size=64',
    villaName: 'Villa Sawah Ubud',
    lastMessageAt: '2026-05-18T14:32:00Z',
    unreadCount: 2,
    messages: [
      { id: 'msg-1-1', sender: 'guest', textZh: '你好，请问6月12日到6月19日别墅还有空房吗？我们两人，想要一个安静的假期。', textEn: 'Hello, is the villa available from June 12 to June 19? There are two of us, looking for a quiet retreat.', sentAt: '2026-05-17T09:15:00Z', translated: true },
      { id: 'msg-1-2', sender: 'host', textEn: "Hi! Great news — those dates are available. Villa Sawah is perfect for couples seeking peace. The rice terraces are at their most beautiful in June. Shall I hold the dates for you?", textZh: '您好！好消息——那些日期有空房。稻田别墅非常适合寻求宁静的情侣。六月份的稻田景色最为美丽。我帮您预留那几天吗？', sentAt: '2026-05-17T09:48:00Z', translated: true },
      { id: 'msg-1-3', sender: 'guest', textZh: '太好了！请问可以安排私人厨师吗？我们希望有一顿特别的晚餐。', textEn: 'Great! Can a private chef be arranged? We would like one special dinner.', sentAt: '2026-05-17T10:02:00Z', translated: true },
      { id: 'msg-1-4', sender: 'host', textEn: "Absolutely! Our chef Kadek specialises in both Balinese and Chinese cuisine. A 4-course dinner for two runs around Rp 800,000 (≈ ¥370). I can arrange flowers and candles by the pool at no extra charge — just say the word.", textZh: '当然可以！我们的厨师Kadek擅长巴厘岛和中式菜肴。两人四道菜晚餐约Rp 800,000（约¥370）。我可以免费在泳池旁布置鲜花和蜡烛——告诉我一声就好。', sentAt: '2026-05-17T10:31:00Z', translated: true },
      { id: 'msg-1-5', sender: 'guest', textZh: '非常好！我们今天就预订。谢谢您的热情款待。', textEn: 'Perfect! We will book today. Thank you for your warm hospitality.', sentAt: '2026-05-17T10:45:00Z', translated: true },
      { id: 'msg-1-6', sender: 'host', textEn: "Wonderful! I've noted the chef dinner request. On arrival day, I'll be there personally to welcome you and show you around. Welcome to Villa Sawah — we can't wait to host you.", textZh: '太棒了！我已记下厨师晚餐的要求。抵达当天，我会亲自迎接您并带您参观。欢迎来到稻田别墅——我们迫不及待地等待接待您。', sentAt: '2026-05-17T11:05:00Z', translated: true },
      { id: 'msg-1-7', sender: 'guest', textZh: '请问别墅距离乌布市场有多远？', textEn: 'How far is the villa from the Ubud market?', sentAt: '2026-05-18T14:20:00Z', translated: true },
      { id: 'msg-1-8', sender: 'host', textEn: "About 15 minutes by scooter (I can arrange one for you), or 30 minutes by car. The morning market at Ubud is best visited early — around 6am before the tour groups arrive.", textZh: '骑摩托车约15分钟（我可以为您安排），或乘车约30分钟。乌布早市最好早去——大约早上6点，在旅游团到达之前。', sentAt: '2026-05-18T14:32:00Z', translated: false },
    ],
  },
  {
    id: 'conv-2',
    villaId: 'villa-6',
    guestId: 'guest-002',
    hostId: 'host-1',
    guestName: '林敏',
    hostName: 'Wayan Sudana',
    guestAvatar: av('林敏', '9BB8B0'),
    hostAvatar: 'https://ui-avatars.com/api/?name=Wayan+Sudana&background=1F6B5C&color=fff&size=64',
    villaName: 'Villa Bukit Nusa Dua',
    lastMessageAt: '2026-05-19T10:15:00Z',
    unreadCount: 0,
    messages: [
      { id: 'msg-2-1', sender: 'guest', textZh: '你好！我们是一个12人的企业团队，想要7月10日到17日入住。请问有什么特别的团建活动可以安排？', textEn: "Hi! We're a corporate group of 12 and want to stay July 10–17. Can any team-building activities be arranged?", sentAt: '2026-05-18T08:20:00Z', translated: true },
      { id: 'msg-2-2', sender: 'host', textEn: "Hello! Villa Bukit is perfect for corporate groups — our 25m pool, large dining terrace, and private beach path give you space to relax and connect. I can arrange: group cooking class, sunrise yoga, surfing lessons, or a Balinese ceremony experience. Which interests your team?", textZh: '您好！布基特别墅非常适合企业团队——我们的25米泳池、大型餐饮露台和私人海滩通道为您提供放松和交流的空间。我可以安排：团体烹饪课、日出瑜伽、冲浪课或巴厘岛仪式体验。您的团队对哪些感兴趣？', sentAt: '2026-05-18T09:05:00Z', translated: true },
      { id: 'msg-2-3', sender: 'guest', textZh: '烹饪课和瑜伽课听起来很好！另外，我们需要一个投影仪用于一个简短的演示。可以安排吗？', textEn: "The cooking class and yoga sound great! We also need a projector for a short presentation. Can that be arranged?", sentAt: '2026-05-18T09:40:00Z', translated: true },
      { id: 'msg-2-4', sender: 'host', textEn: "Of course! I'll set up a projector and screen in the covered pavilion — it's ideal for presentations with the pool as a backdrop. For the cooking class I'll bring in Chef Wayan (specialises in Balinese cuisine). Yoga at sunrise on the beach terrace. I'll have everything confirmed by tomorrow.", textZh: '当然！我将在有遮挡的凉亭内设置投影仪和屏幕——以泳池为背景，非常适合演示。烹饪课我将邀请Wayan厨师（专门从事巴厘岛菜肴）。日出瑜伽在海滩露台上进行。我明天前确认所有安排。', sentAt: '2026-05-19T10:15:00Z', translated: true },
    ],
  },
  {
    id: 'conv-3',
    villaId: 'villa-11',
    guestId: 'guest-003',
    hostId: 'host-1',
    guestName: '赵晓丽',
    hostName: 'Wayan Sudana',
    guestAvatar: av('赵晓丽', 'C9A961'),
    hostAvatar: 'https://ui-avatars.com/api/?name=Wayan+Sudana&background=1F6B5C&color=fff&size=64',
    villaName: 'Villa Sindhu Sanur',
    lastMessageAt: '2026-05-17T16:30:00Z',
    unreadCount: 1,
    messages: [
      { id: 'msg-3-1', sender: 'guest', textZh: '您好！我们有两个小孩（3岁和6岁）。泳池对他们来说安全吗？有没有救生圈之类的设备？', textEn: 'Hello! We have two small children (3 and 6 years old). Is the pool safe for them? Are there life rings or similar equipment?', sentAt: '2026-05-16T14:20:00Z', translated: true },
      { id: 'msg-3-2', sender: 'host', textEn: "Hello! Villa Sindhu is our most family-friendly property — the pool has a dedicated shallow end (40cm) perfect for small children. We provide floaties, water wings, and a pool net for safety. There's also a secure perimeter fence around the pool that can be installed on request. Your children will be safe and happy!", textZh: '您好！辛度别墅是我们最适合家庭的物业——泳池有专门的浅水区（40厘米深），非常适合小孩子。我们提供浮圈、水上臂圈和安全泳池网。如需还可安装泳池周围的安全围栏。您的孩子一定安全快乐！', sentAt: '2026-05-16T15:10:00Z', translated: true },
      { id: 'msg-3-3', sender: 'guest', textZh: '太好了！还有一个问题：附近有没有好的儿童餐厅或超市？', textEn: "That's wonderful! One more question: are there any good child-friendly restaurants or supermarkets nearby?", sentAt: '2026-05-17T09:00:00Z', translated: true },
      { id: 'msg-3-4', sender: 'host', textEn: "Sanur is perfect for families! Hardy's supermarket is 5 minutes by car (they have everything). For restaurants, Massimo (Italian, kid-friendly) is a 10-minute walk, and Café Batu Jimbar is great for breakfast with children. I'll prepare a full local guide for your arrival.", textZh: '沙努尔非常适合家庭！Hardy\'s超市开车5分钟（应有尽有）。餐厅方面，Massimo（意大利风格，儿童友好）步行10分钟可达，Café Batu Jimbar是带孩子吃早餐的好去处。我将为您抵达时准备完整的当地指南。', sentAt: '2026-05-17T16:30:00Z', translated: false },
    ],
  },
];

// ─── INSIGHTS DATA ────────────────────────────────────────────────────────────

export const REVENUE_TREND = [
  { month: 'Jun 2025', revenueIdr: 28500000 },
  { month: 'Jul 2025', revenueIdr: 42000000 },
  { month: 'Aug 2025', revenueIdr: 38500000 },
  { month: 'Sep 2025', revenueIdr: 31000000 },
  { month: 'Oct 2025', revenueIdr: 45000000 },
  { month: 'Nov 2025', revenueIdr: 52000000 },
  { month: 'Dec 2025', revenueIdr: 68000000 },
  { month: 'Jan 2026', revenueIdr: 55000000 },
  { month: 'Feb 2026', revenueIdr: 48000000 },
  { month: 'Mar 2026', revenueIdr: 61000000 },
  { month: 'Apr 2026', revenueIdr: 74000000 },
  { month: 'May 2026', revenueIdr: 82000000 },
];

export const OCCUPANCY_TREND = [
  { month: 'Jun 2025', occupancy: 62 },
  { month: 'Jul 2025', occupancy: 78 },
  { month: 'Aug 2025', occupancy: 71 },
  { month: 'Sep 2025', occupancy: 58 },
  { month: 'Oct 2025', occupancy: 82 },
  { month: 'Nov 2025', occupancy: 88 },
  { month: 'Dec 2025', occupancy: 95 },
  { month: 'Jan 2026', occupancy: 87 },
  { month: 'Feb 2026', occupancy: 76 },
  { month: 'Mar 2026', occupancy: 83 },
  { month: 'Apr 2026', occupancy: 91 },
  { month: 'May 2026', occupancy: 89 },
];

export const BOOKING_SOURCES = [
  { name: 'Search', value: 54 },
  { name: 'Direct', value: 28 },
  { name: 'Wishlist', value: 18 },
];

export const PAYOUTS = [
  { id: 'pay-1', date: '2026-05-01', amountIdr: 82500000, method: 'Bank transfer · BCA ****4821', status: 'completed', reference: 'BVP-2026-0501' },
  { id: 'pay-2', date: '2026-04-01', amountIdr: 74000000, method: 'Bank transfer · BCA ****4821', status: 'completed', reference: 'BVP-2026-0401' },
  { id: 'pay-3', date: '2026-03-01', amountIdr: 61000000, method: 'Bank transfer · BCA ****4821', status: 'completed', reference: 'BVP-2026-0301' },
  { id: 'pay-4', date: '2026-02-01', amountIdr: 48000000, method: 'Bank transfer · BCA ****4821', status: 'completed', reference: 'BVP-2026-0201' },
  { id: 'pay-5', date: '2026-01-01', amountIdr: 55000000, method: 'Bank transfer · BCA ****4821', status: 'completed', reference: 'BVP-2026-0101' },
  { id: 'pay-6', date: '2025-12-01', amountIdr: 68000000, method: 'Bank transfer · BCA ****4821', status: 'completed', reference: 'BVP-2025-1201' },
];
